var langs = [{
	mi_home: "Home",
	mi_about: "About me",
	mi_skills: "Skills",
	mi_portf: "Portfolio",
	mi_cont: "Contacts",
	fio: "Denis Novik",
	info: "UX&nbsp;|&nbsp;UI&nbsp;designer 24&nbsp;years old, Minsk",
	fio: "Denis Novik",
	about_p1: "Hi, I'm Denis – UX/UI designer from Minsk. I'm&nbsp;interested&nbsp;in&nbsp;design and everything connected with it.",
	about_p2: "I'" + 'm studying at courses "Web and mobile design interfaces" in IT-Academy.',
	about_p3: "Ready to implement excellent projects with&nbsp;wonderful&nbsp;people.",
	skills_pre: "I work in such programs as",
	footer_text: "Want to know more or just chat? You&nbsp;are&nbsp;welcome!",
	footer_btn: "Send message",
	footer_soc: "Like me on LinkedIn,&nbsp;Instagram,&nbsp;Behance, Dribble"
},{
	mi_home: "Головна",
	mi_about: "Про мене",
	mi_skills: "Навички",
	mi_portf: "Портфоліо",
	mi_cont: "Контакти",
	fio: "Денис Новік",
	info: "UX&nbsp;|&nbsp;UI&nbsp;дизайнер 24&nbsp;роки, Мінськ",
	about_p1: "Привіт, я Денис – UX/UI дизайнер з Мінська. Я&nbsp;цікавлюсь&nbsp;дизайном та всім, що з ним пов'язане.",
	about_p2: 'Я навчаюсь на курсах "Web and mobile design interfaces" в IT-Академії.',
	about_p3: "Готовий реалізовувати чудові проекти із&nbsp;прекрасними&nbsp;людьми.",
	skills_pre: "Працюю в таких програмах як",
	footer_text: "Хочете взнати більше чи просто поспілкуватись? Ласкаво&nbsp;прошу!",
	footer_btn: "Надіслати повідомлення",
	footer_soc: "Я у соцмережах LinkedIn,&nbsp;Instagram,&nbsp;Behance, Dribble"
}]